name: update-release-notes
on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  update-release-notes:
    runs-on: thevickypedia-lite
    steps:
      - uses: actions/checkout@v4
      - name: Install Gitverse
        run: |
          python -m pip install --upgrade pip
          python -m pip install gitverse
          gitverse_version=$(gitverse --version)
          echo "::notice title=gitverse version::${gitverse_version}"
        shell: bash
      - name: Generate Release Notes
        run: |
          gitverse-release reverse -f release_notes.rst -t 'Release Notes'
        shell: bash
      - name: Commit and Push Changes
        # https://github.com/orgs/community/discussions/26560
        run: |
          git diff --no-prefix --unified=0
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add release_notes.rst
          if ! git diff --cached --quiet; then
            echo "::notice title=Changes detected::Committing and pushing changes to release notes."
            git commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m "Update release notes"
            git push origin main
          else
            echo "::warning title=No update::The release notes file has not changed, skipping commit and push."
          fi
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
